### ISSUE TITLE
[Feature request] Scroll to specified plugin in community plugins tab

### ISSUE THREAD

**Issue by huachuman** [javalent/settings-search#34]
When I click the arrow, I expect to be taken to the plugin's settings, or at least have it highlighted in the community plugins page. As it stands, it just takes me to the top of the community plugins page and gets me to search again from there. 

In my view this is a bug even though I submitted it as a feature request. Any plans on fixing this?

**Comment by sigrunixia** [comment]
@huachuman 

It is not quite clear what steps you are taking and when. Are you able to write it out start to finish, or record a gif/video to explain exactly what it is you are requesting?

**Comment by huachuman** [comment]
Clicking the arrow on the right should take me to the plugin's card, or similar, but instead, it just takes me to the community plugins search box. 

![image](https://user-images.githubusercontent.com/125603964/234564835-cb42b4d3-b712-41e9-bb56-bb106071f670.png)
![image](https://user-images.githubusercontent.com/125603964/234564828-59e567db-1fd1-459c-97ab-c180258afa34.png)

**Comment by sigrunixia** [comment]
> I expect that when I click the arrow on the right it should scroll to the plugin's card and highlight it, or something along those lines, but instead, it just takes me to the community plugins search box.
> 
> Here's an example result from a search I did with settings-search ![image](https://user-images.githubusercontent.com/125603964/234564835-cb42b4d3-b712-41e9-bb56-bb106071f670.png)
> 
> Here's where clicking the arrow takes me ![image](https://user-images.githubusercontent.com/125603964/234564828-59e567db-1fd1-459c-97ab-c180258afa34.png)
> 
> That plugin also has a settings icon in the community plugins page but it's not showing up in the settings-search results (see first image) where it should, beside the arrow: ![image](https://user-images.githubusercontent.com/125603964/234566567-184e5a9c-362c-43bd-a285-5932d2e45b6d.png)

That is odd behavior indeed. I am not sure why you are brought back to the community page unless you deliberately ask for it, as I show in my gif below in the dataview example. 

![settings-search](https://user-images.githubusercontent.com/68425372/235211088-a5458bf1-6df4-4feb-bafc-ba71f5e76e6e.gif)

As far as Emoji Shortcodes settings not showing up in Setting Search, that would be something that the author may need to enable. I'll check to see if they have dynamic searching enabled, and if not, make a FR over there.

**Comment by Th0rGarden** [comment]
I'm having the same issue. Search in the search box and click the arrow and it just loads the regular community plugins list but does not scroll to the plugin or anything.
