### ISSUE TITLE
🐞 Latest version of settings-search causes other plugins to error loading.

### ISSUE THREAD

**Issue by andreicozma1** [javalent/settings-search#43]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

All other plugins should load correctly when this plugin is enabled

### Current behaviour

Latest version prevents certain plugins from loading correctly. 
For example, the smart connections plugin does not load with Settings Search enabled. Disabling Settings Search fixes this issue, and Smart Connections loads correctly.

```
caught (in promise) TypeError: Cannot read properties of undefined (reading 'includes')
    at t.eval (plugin:settings-search:266:54)
    at t.wrapper [as addSettingTab] (plugin:settings-search:59:20)
    at t.addSettingTab (app.js:1:2028572)
    at SmartConnectionsPlugin.initialize (plugin:smart-connections:511:10)
```

### Reproduction

1. Install Smart Connections 1.6.34 (though I am sure this could happen to other plugins as well, since disabling Settings Search fixes the loading issue)
2. Verify that plugin works correctly. It does
3. Install Settings Search 1.3.9
4. Plugin no longer loads properly. Console shows the above exception. We notice settings cog for Smart Connections dissapears
5. Disable Settings Search
6. Reload Obsidian
7. Observe that plugin loads correctly

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [X] Linux
- [ ] macOS
- [ ] Windows

### Obsidian Version Check

1.4.14

### Plugin Version

1.3.9

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by srun007** [comment]
same problem ，hope to fix soon
